# Generated by Django 3.1.7 on 2021-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='type',
            field=models.CharField(choices=[('g', 'Gather'), ('d', 'Discuss')], default='g', max_length=1),
        ),
    ]
